apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- ingress.yaml

configMapGenerator:
- name: homer-config
  files:
  - data/config.yml

labels:
- pairs:
    app: homer
    component: dashboard
