apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc.yaml
- ingress.yaml

commonLabels:
  app: homer

namespace: homer

images:
- name: b4bz/homer
  newTag: v25.05.2
