helmDefaults:
  wait: true
  timeout: 600
  createNamespace: true

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: nginx-ingress
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: "~4.8.0"
  values:
  - controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      config: {}
