networks:
  reverse_proxy:
    external: true
    driver: overlay

services:
  ollama:
    image: ollama/ollama:0.2.2
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama

  speech:
    image: ghcr.io/matatonic/openedai-speech:0.17.2
    restart: unless-stopped
    init: true
    # ports: [8000:8000]
    # env_file: .env
    environment:
      - TZ=America/Chicago
      - TTS_HOME=voices
      - HF_HOME=voices
      # - PRELOAD_MODEL=xtts
      # - PRELOAD_MODEL=xtts_v2.0.2
      # - PRELOAD_MODEL=parler-tts/parler_tts_mini_v0.1
    volumes:
      - ./tts-voices:/app/voices
      - ./tts-config:/app/config

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.3.8
    restart: unless-stopped
    depends_on: [ollama, speech]
    networks: [default, reverse_proxy]
    env_file: .env
    init: true
    volumes:
      - ./open-webui:/app/backend/data
    # ports: [18080:8080]
    environment:
      - TZ=America/Chicago
      - OLLAMA_BASE_URL=http://ollama:11434
    labels:
      - swag=enable
      - swag_address=open-webui
      - swag_url=ai.*
