model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: claude-3.5
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: perplexity
    litellm_params:
      model: perplexity/llama-3.1-sonar-small-128k-online
      api_key: os.environ/PERPLEXITY_API_KEY

litellm_settings:
    drop_params: true
#   cache: True          # set cache responses to True, litellm defaults to using a redis cache
