networks:
  reverse_proxy:
    external: true
    driver: overlay

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 50m
    max-file: 1

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.67.4-stable
    restart: unless-stopped
    init: true
    logging: *default-logging
    volumes:
      - ./config.yaml:/app/config.yaml
    env_file: [.env]
    ports: [14000:4000]
    command: --config /app/config.yaml --detailed_debug
    networks: [reverse_proxy, default]
