networks:
  reverse_proxy:
    external: true
    driver: overlay

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 50m
    max-file: 1

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.57.0
    restart: unless-stopped
    init: true
    logging: *default-logging
    volumes:
      - ./config.yaml:/app/config.yaml
    env_file: [.env]
    # environment:
      # - REDIS_HOST=redis
      # - LITELLM_LOG=DEBUG
    ports: [14000:4000]
    command: --config /app/config.yaml --detailed_debug
    networks: [reverse_proxy, default]

  # redis:
  #   image: redis:alpine
  #   command: --save 60 1 --loglevel warning
  #   restart: unless-stopped
  #   logging: *default-logging
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
  #     start_period: 20s
  #     interval: 30s
  #     retries: 5
  #     timeout: 3s
  #   volumes:
  #     - ./redis:/data

#   db:
#     image: postgres:17-alpine
#     restart: unless-stopped
#     environment:
#       - POSTGRES_USER=litellm
#       - POSTGRES_PASSWORD=litellm
#       - POSTGRES_DB=litellm
#     volumes:
#       - ./postgres17:/var/lib/postgresql/data
