name: nextcloud

volumes:
  redis-data:

networks:
  private:
  reverse_proxy:
    external: true
    driver: overlay

services:
  app:
    image: lscr.io/linuxserver/nextcloud:30.0.3
    restart: unless-stopped
    container_name: nextcloud
    depends_on: [db, redis]
    networks: [private, reverse_proxy]
    # ports:
    #   - 30001:80
    env_file: [db.env]
    environment:
      - TZ=America/Chicago
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
    volumes:
      - ./nextcloud:/config
      - /mnt/user/nextcloud:/data
    labels:
      - swag=enable
      - swag_url=cloud.*
      - swag_port=80
      - swag_proto=http

  db:
    image: lscr.io/linuxserver/mariadb:10.11.10
    restart: unless-stopped
    networks: [private]
    env_file: [db.env]
    environment:
      - TZ=America/Chicago
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
    volumes:
      - ./mariadb:/config

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    networks: [private]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis-data:/data
