name: nextcloud

volumes:
  redis-data:

networks:
  reverse_proxy:
    external: true
    driver: overlay

services:
  app:
    image: lscr.io/linuxserver/nextcloud:31.0.0
    restart: unless-stopped
    container_name: nextcloud
    depends_on: [db, redis]
    networks: [default, reverse_proxy]
    # ports:
    #   - 30001:80
    env_file: [db.env]
    environment:
      - TZ=America/Chicago
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
    volumes:
      - ./nextcloud:/config
      - /mnt/user/nextcloud:/data
    labels:
      - swag=enable
      - swag_url=cloud.*
      - swag_port=80
      - swag_proto=http

  db:
    image: mariadb:11.7
    restart: unless-stopped
    env_file: [db.env]
    user: $DOCKER_UID:$DOCKER_GID
    environment:
      - TZ=America/Chicago
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis-data:/data
