name: immich

networks:
  reverse_proxy:
    external: true
    driver: overlay
  borgmatic_backup:
    external: true

x-logging: &logging
  driver: json-file
  options:
    max-file: "1"
    max-size: "50m"

services:
  server:
    image: ghcr.io/immich-app/immich-server:v1.134.0
    restart: unless-stopped
    logging: *logging
    depends_on: [redis, database]
    env_file: [.env]
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    # ports: [2283:2283]
    networks:
      default:
      reverse_proxy:
        aliases: [immich]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/photos/immich:/usr/src/app/upload
      # Override some paths for SSD performance
      - ./upload/thumbs:/usr/src/app/upload/thumbs
      - ./upload/profile:/usr/src/app/upload/profile
    labels:
      - swag=enable
      - swag_url=photos.*

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.134.0
    restart: unless-stopped
    logging: *logging
    env_file: [.env]
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    volumes:
      - ./ml/.config:/.config
      - ./ml/.cache:/.cache
      - ./ml/cache:/cache

  redis:
    image: redis
    restart: unless-stopped
    logging: *logging
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - ./redis:/data

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    restart: unless-stopped
    networks:
      default:
      borgmatic_backup:
        aliases: [immich-database]
    logging: *logging
    env_file: [.env]
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ./db:/var/lib/postgresql/data
