networks:
  reverse_proxy:
    external: true
    driver: overlay

services:
  app:
    image: louislam/uptime-kuma:1.23.16
    restart: unless-stopped
    container_name: uptime
    networks: [reverse_proxy]
    # ports:
    #   - 3001:3001
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
    # NOTE: Cannot use auto proxy here since we need to use two subdomains!
    # labels:
    #   - swag=enable
    #   - swag_url=uptime.*
