networks:
  reverse_proxy:
    external: true
    # driver: overlay

services:
  app:
    image: louislam/uptime-kuma:1.23.16
    restart: unless-stopped
    container_name: uptime-kuma
    networks: [reverse_proxy]
    # ports: [3001:3001]
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
    labels:
      - swag=enable
      - swag_auth=authentik
      - swag_url=uptime.*
