networks:
  reverse_proxy:
    external: true
    #driver: overlay
  dockerproxy:

x-logging: &logging
  driver: json-file
  options:
    max-file: "1"
    max-size: "5m"

services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
    restart: unless-stopped
    container_name: dockerproxy
    networks: [dockerproxy]
    logging: *logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0

  swag:
    image: ghcr.io/linuxserver/swag:4.2.0
    restart: unless-stopped
    container_name: swag
    networks: [reverse_proxy, dockerproxy]
    depends_on: [dockerproxy]
    logging: *logging
    ports:
      - 30080:80
      - 30443:443
    volumes:
      - ./config:/config
    env_file: [.env]
    environment:
      TZ: America/Chicago
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      DOCKER_HOST: dockerproxy
      DOCKER_MODS: >-
        linuxserver/mods:universal-docker|
        linuxserver/mods:swag-auto-proxy
