services:
  app:
    image: cloudflare/cloudflared:2025.6.0
    container_name: cloudflared
    network_mode: host
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "cloudflared tunnel info ${TUNNEL_NAME} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
