networks:
  private:
  reverse_proxy:
    external: true
    driver: overlay

volumes:
  pgdata2:

services:
  api:
    image: ghcr.io/danny-avila/librechat:v0.7.2
    restart: unless-stopped
    user: $DOCKER_UID:$DOCKER_GID
    depends_on:
      - mongodb
      - rag_api
    ports:
      - "${PORT}:${PORT}"
    networks:
      private:
      reverse_proxy:
        aliases:
          - librechat
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
      - ./uploads:/app/uploads/temp
      - ./librechat.yaml:/app/librechat.yaml
    labels:
      - swag=enable
      - swag_address=librechat
      - swag_url=ai.*

  mongodb:
    image: mongo:7.0.11
    restart: unless-stopped
    networks:
      - private
    user: $DOCKER_UID:$DOCKER_GID
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.7.3
    restart: unless-stopped
    networks:
      - private
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data

  vectordb:
    image: ankane/pgvector:v0.5.1
    restart: unless-stopped
    networks:
      - private
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest@sha256:718b7f92d0ac4ee921cda6f16867b38e2a0b6da6c5f59b865bc909fda68aba29
    restart: unless-stopped
    networks:
      - private
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    depends_on:
      - vectordb
    env_file:
      - .env
