networks:
  reverse_proxy:
    external: true
    driver: overlay

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 1m
    max-file: 1

services:
  api:
    image: ghcr.io/danny-avila/librechat:v0.7.7
    restart: unless-stopped
    user: $DOCKER_UID:$DOCKER_GID
    depends_on: [mongodb, rag_api]
    logging: *default-logging
    # ports:
    #   - "${PORT}:${PORT}"
    networks:
      default:
      reverse_proxy:
        aliases:
          - librechat
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
      - ./app-data:/app/data
      - ./uploads:/app/uploads/temp
      - ./librechat.yaml:/app/librechat.yaml
    labels:
      - swag=enable
      - swag_address=librechat
      - swag_url=ai.*

  mongodb:
    image: mongo:7.0.17
    restart: unless-stopped
    user: $DOCKER_UID:$DOCKER_GID
    logging: *default-logging
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    user: $DOCKER_UID:$DOCKER_GID
    logging: *default-logging
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.13:/meili_data

  vectordb:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    logging: *default-logging
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./vectordb_pg16:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:v0.4.0
    restart: unless-stopped
    depends_on: [vectordb]
    logging: *default-logging
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=8000
    env_file:
      - .env
