volumes:
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  pbf:
    image: kometateam/imagemaid:v1.1.1
    network_mode: bridge
    user: $DOCKER_UID:$DOCKER_GID
    init: true
    environment:
      - TZ=America/Chicago
    volumes:
      - ./data:/config
      - /mnt/fast/docker/media/plex/config:/plex
      - tmp:/tmp
