name: stash

networks:
  reverse_proxy:
    external: true
    driver: overlay

services:
  app:
    image: stashapp/stash:v0.25.1
    container_name: stash
    restart: unless-stopped
    ## Non-root not supported. See:
    ## https://github.com/stashapp/stash/issues/4300
    ## https://github.com/stashapp/stash/issues/684
    # user: $DOCKER_UID:$DOCKER_GID
    ## the container's port must be the same with the STASH_PORT in the environment section
    # ports:
    #   - "9999:9999"
    networks: [reverse_proxy]
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash

      ## Keep configs, scrapers, and plugins here.
      - ./config:/root/.stash
      ## Point this at your collection.
      - /mnt/user/game-logs:/data
      ## This is where your stash's metadata lives
      - ./metadata:/metadata
      ## Any other cache content.
      - ./cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ./blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./generated:/generated
    labels:
      - swag=enable
      - swag_auth=authentik
