name: filerun

networks:
  reverse_proxy:
    external: true
    # driver: overlay
  borgmatic_backup:
    external: true

volumes:
  esearch:

x-logging: &logging
  driver: json-file
  options:
    max-file: "1"
    max-size: "50m"

services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    logging: *logging
    networks:
      default:
      borgmatic_backup:
        aliases: [filerun-database]
    environment:
      MARIADB_DATABASE: filerun
      MARIADB_USER: db
      MARIADB_PASSWORD: db
      MARIADB_ROOT_PASSWORD: db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: filerun/filerun:8.1
    restart: unless-stopped
    depends_on: [db]
    networks: [reverse_proxy, default]
    logging: *logging
    hostname: filerun
    # ports: [10080:80]
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: db
      FR_DB_PASS: db
      APACHE_RUN_USER: $DOCKER_UID
      APACHE_RUN_USER_ID: $DOCKER_UID
      APACHE_RUN_GROUP: $DOCKER_GID
      APACHE_RUN_GROUP_ID: $DOCKER_GID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./html:/var/www/html
      - /mnt/user/filerun:/user-files
    labels:
      swag: enable
      swag_url: cloud.*
      swag_port: 80
      swag_proto: http
      deck-chores.filerun.command: php /var/www/html/cron/process_search_index_queue.php
      deck-chores.filerun.interval: 5m

  tika:
    image: logicalspark/docker-tikaserver
    restart: unless-stopped
    logging: *logging

  esearch:
    image: elasticsearch:8.19.1
    restart: unless-stopped
    hostname: elasticsearch
    logging: *logging
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - esearch:/usr/share/elasticsearch/data
